/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:805a282f-db37-4737-a162-3fa8fd4aaf2f",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_HegVColeh",
    "aws_user_pools_web_client_id": "5harri2v3avv01etildvgsuepr",
    "oauth": {}
};


export default awsmobile;
